# Generated by Django 3.2.5 on 2025-03-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='generated_faces/')),
                ('enhanced_image', models.ImageField(blank=True, null=True, upload_to='enhanced_faces/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
